### ISSUE TITLE
"Cannot cast from source type to destination type"

### ISSUE THREAD

**Issue by nixtwiz** [oddgames/UIToolkit#106]
Whenever I try to set up UIToolkit I get an "InvalidCastException: Cannot cast from source type to destination type." error. I've just started using UIToolkit so I don't know much about it, but I'm pretty sure I've got everything set up right. My TexturePacker file was renamed to a .txt, so its not that. When I double click the error it takes me to this line of code in the UISpriteManager script:
"var frames = (Hashtable)decodedHash["frames"];"

Any ideas?

**Comment by prime31** [comment]
best to post questions like this in the forum.
