### ISSUE TITLE
iphone not respecting rotation

### ISSUE THREAD

**Issue by PapaWhiskey65** [oddgames/UIToolkit#111]
running on iphone, game only supports landscape, UIToolkit will display portrait in landscape mode

**Comment by prime31** [comment]
Unity has a rotation bug that will be fixed in the next update. Currently the workaround is to not run any code until Unity is properly in your desired orientation.

**Comment by PapaWhiskey65** [comment]
wonderful...odd that it only happens on iphone and not ipad.

so just sit and spin in some script till unity is initialized?

**Comment by PapaWhiskey65** [comment]
and it's only uitoolkit that is not respecting the rotation....unity is properly rotated.

**Comment by prime31** [comment]
Check the Unity forums. There are a couple threads detailing the
issue. Your symptoms are 100% in line with the bug.

Mike

On May 24, 2012, at 8:57 AM, WreckCenter
reply@reply.github.com
wrote:

**Comment by PapaWhiskey65** [comment]
been searching the forums (and googling) quite a bit, guess i havent used the right search terms...i've found issues with autorotation and unity but supposedly they fixed em in 3.4...this issue appears to be only with uitoolkit...i'll search some more

Phil

**Comment by prime31** [comment]
The thread is right on the front page. UIToolkit doesn't do anything magical. All it does is make a camera. It isn't even possible for it to swap orientations on its own.
