### ISSUE TITLE
scrollable containers disappear

### ISSUE THREAD

**Issue by PapaWhiskey65** [oddgames/UIToolkit#113]
create a vertical scroll container, add some images, run on device, touch the buttons, 30-40% of the time (or higher) the scroller will disappear due to all the container values getting messed up, sprites getting bad positions, etc...essentially everything gets clipped so it disappears...i've seen NaN for _scrollPosition in the debugger, not sure why it's happening

**Comment by PapaWhiskey65** [comment]
commenting out decelerate fixes the bug, but thats not a solution

**Comment by PapaWhiskey65** [comment]
somehow velocites.count is 0 which causes a divide by zero, which causes the NaN...adding a check for _velocities.count <= 0 fixes it for me, but is it a bug that velocities.count is zero?

**Comment by cbaltzer** [comment]
Change line 128 of UIAbstractTouchableContainer.cs from

```
var avgVelocity = total / _velocities.Count;
```

to

```
var avgVelocity = (_velocities.Count > 0) ? total / _velocities.Count : total;
```

**Comment by PapaWhiskey65** [comment]
that wont work...if velocites.count = 0, then total will = 0, and you'll still have a divide by zero/NaN condition

edit: ahhh nevermind i see it removing the divide and just setting avgVel to 0...my bad

question remains...why are we in decelerate with no velocity? are we masking a bug with this "fix"?
