### ISSUE TITLE
sorting is broken (randomly) on device

### ISSUE THREAD

**Issue by PapaWhiskey65** [oddgames/UIToolkit#114]
havent tracked it down yet...ipod/iphone will sort incorrectly once, then be fine (most of the time)...ipad build sorts incorrectly all the time, even though fine in editor and fine in xcode

**Comment by PapaWhiskey65** [comment]
Unity appears to randomly return the list of components on a child, so in UI.cs, the order of toolkits is unknown, so if a button toolkit renders before the background it's overlayed on, the buttons will blend with whatever is in the buffer instead of the proper background. I added sorting code to UI.cs and am testing now and will send a pull request after testing

**Comment by PapaWhiskey65** [comment]
after adding the toolkit sort, it "looked" like it was all good...great in editor, great running from xcode, but archive it, make an ipa, load the ipa onto device, and now only on the first run of the app is the sorting wrong...stumped

**Comment by numaiomul** [comment]
in the UI.cs script do this:
            GameObject tempGameObject;
            tempGameObject = GameObject.Find("UIToolkitInterface"); 
            firstToolkit = tempGameObject.GetComponent<UIToolkit>();
            tempGameObject = GameObject.Find("UIToolkitText"); 
            myToolkit1 = tempGameObject.GetComponent<UIToolkit>();
            tempGameObject = GameObject.Find("UIToolkitButton");
            myToolkit2 = tempGameObject.GetComponent<UIToolkit>();
            if(tempGameObject = GameObject.Find("UIToolkitInterface2")) //if interface does not exist it will nor bug out
                    myToolkit3 = tempGameObject.GetComponent<UIToolkit>(); 
            tempGameObject = null;

This way you force it to make the right decision all the time :) [this is way it works on all platform]

**Comment by PapaWhiskey65** [comment]
actually my sort code is the same thing as long as you set the layers
but
adding +1 +2 etc to shader tag queue = transparent fixes it
