### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by redchair123** [oddgames/UIToolkit#155]
when do you plan on having a license, and what's wrong with a standard open source license?

**Comment by prime31** [comment]
You can consider the license to be: Do whatever you want with UIToolkit except sell it or include it in any commercial game asset. It is free and it can be given away as is or modified in any other free asset.

**Comment by redchair123** [comment]
Why not [CC-BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US)?

**Comment by prime31** [comment]
CC-BY-NC-SA would be totally fine. I'll update the Github page.

**Comment by robertwahler** [comment]
@prime31, I don't think that license is appropriate without customization if you intend for your library to be used in a commercial game (the NC part).

**Comment by redchair123** [comment]
@robertwahler read the first response: "**Do whatever you want** with UIToolkit **except** sell it or **include it in any commercial game asset**". Based on the verbiage, it sounds like NC is appropriate here, although it really is @prime31's decision

**Comment by robertwahler** [comment]
@Niggler, thanks, I did read that. That is why I chimed in here. The problem is that a response in an issue thread isn't a license.  The license is clearly stated as CC-BY-NC-SA in the project's readme. The way I read that license, you need to negotiate with the holder to use it in any commercial product. I agree that that doesn't seem to be @prime31 intent.

**Comment by redchair123** [comment]
@robertwahler the license does not permit you to use the project assets in a commercial setting.  Full stop.  For commercial uses, @prime31 is free to license under a different set of terms which does permit game use (and can charge for releasing under that license to others). 

Consider HighCharts (http://shop.highsoft.com/highcharts.html) which has a non-commercial license (CC BY-NC) and a commercial license

**Comment by prime31** [comment]
UIToolkit (and all of my code on GitHub) is absolutely free to use in any game that you release. The only restriction is that you cannot sell it as a game asset or as part of any other game asset.

Mike

On Nov 24, 2013, at 5:24 AM, Robert Wahler notifications@github.com wrote:

@prime31, I don't think that license is appropriate without customization if you intend for your library to be used in a commercial game (the NC part).

**Comment by robertwahler** [comment]
@Niggler, yes, exactly!  I would like @prime31 to explicitly state the separate license in the project's documentation.

**Comment by germinator** [comment]
I certainly appreciate you releasing this.  But I have to agree, the licensing is vague and seemingly contradictory.

**Comment by prime31** [comment]
You are free and clear to use UIToolkit in any game that you want. The only thing you cannot do is sell UIToolkit as a Unity asset or as part of another Unity asset. 

Mike

On Feb 8, 2014, at 2:27 PM, germinator notifications@github.com wrote:

I certainly appreciate you releasing this. But I have to agree, the licensing is vague and seemingly contradictory.

**Comment by fuzzballb** [comment]
So we are allowed to use it in a commercial game, but not make our own UItoolkit based on this one and sell that in the asset store.

**Comment by prime31** [comment]
That is correct. You can use it in any and all of your games. You cannot distribute it outside of your games though.

Mike

On Mar 1, 2014, at 5:29 AM, fuzzballb notifications@github.com wrote:

So we are allowed to use it in a commercial game, but not make our own UItoolkit based on this one and sell that in the asset store.
