### ISSUE TITLE
Mouse Over Bug.

### ISSUE THREAD

**Issue by namoricoo** [oddgames/UIToolkit#21]
In the  UIObject class, I found a Bug that i fixed with a simple Else statement.  Here is the after code for the Mouse over effect. Just delete the current parentUIObject function and paste in this replacement. Or you can just add the else statement. When this is finished. The mouse over will start working correctly.

/// <summary>

    /// Setting the parentUIObject automatically sets up a listener for changes to the tranform.
    /// When the parent transform changes, UISprite's will automatically call updateTransform to keep their
    /// touch frames and actual positions in sync with the parent
    /// </summary>

    public UIObject parentUIObject
    {
        get { return _parentUIObject; }
        set
        {
            if( value == _parentUIObject )
                return;

```
        // remove the old listener if we have one
        if( _parentUIObject != null )
            _parentUIObject.onTransformChanged -= transformChanged;

        // reparent the UIObject in the same UIToolkit tree as it's children
        //if( value != null && value.parent != parent )
        //  value.parent = parent;

        _parentUIObject = value;

        // if we got a null value, then we are being removed from the UIObject so reparent to our manager
        if( _parentUIObject != null )
        {
            clientTransform.parent = _parentUIObject.clientTransform;
        }
        else
        {
            if( this.GetType() == typeof( UISprite ) )
                clientTransform.parent = ((UISprite)this).manager.transform;
            else
                clientTransform.parent = null;
        }

        // add the new listener
        _parentUIObject.onTransformChanged += transformChanged;
    }
}
```

**Comment by FrittenKeeZ** [comment]
I'm pretty sure this is implemented.
Closing this one.

**Comment by namoricoo** [comment]
You can close it if you want to. However, list time I checked the bug
was still there. I've caught and fixed over 10 other bugs big and
small.

On Thu, Feb 2, 2012 at 11:48 AM, Frederik Sauer
reply@reply.github.com
wrote:

**Comment by FrittenKeeZ** [comment]
If you find bugs please open a pull request with your changes.
