### ISSUE TITLE
UISwipeDetector doesn't work on android

### ISSUE THREAD

**Issue by githubbar** [oddgames/UIToolkit#24]
Only Up and Left directions work on Android 3.0. Down and right don't work.
All directions work on Win7

```
void Start () {
    var swipeDetector = UISwipeDetector.create( new Rect( 0, 0, Screen.width, 4*H ), 1);
    swipeDetector.onSwipe += detectedSwipe; 
}

void detectedSwipe( UISwipeDetector sender, SwipeDirection direction )
{
    if (direction == SwipeDirection.Down)
                    // this doesn't work
    if (direction == SwipeDirection.Up)     
        // this works
}
```

The way I fixed it is at line 133 of UISwipeDetector.cs:
......
        // Check the delta move positions.  We can rule out at least 2 directions
        if( touch.deltaPosition.x > 0.0f )
            touchInfo.swipeDetectionState &= ~SwipeDirection.Left;
        if( touch.deltaPosition.x < 0.0f )
            touchInfo.swipeDetectionState &= ~SwipeDirection.Right;

```
    if( touch.deltaPosition.y < 0.0f )
        touchInfo.swipeDetectionState &= ~SwipeDirection.Up;            
    if( touch.deltaPosition.y > 0.0f )
        touchInfo.swipeDetectionState &= ~SwipeDirection.Down;
```

.......

**Comment by mrKaizen** [comment]
I agree - with my android +Gingerbread 2.3.5 (tested on Samsung Galaxy S SCL): RIGHT and DOWN work really bad and late, LEFT and UP perfectly and fast.
The solution seems perfect for me and works as it should.

**Comment by FrittenKeeZ** [comment]
As far as I can see, this is implemented in the main project, right?

**Comment by acron0** [comment]
Has this fix gone in?

**Comment by githubbar** [comment]
I haven't commited it....

**Comment by acron0** [comment]
Why not? :P

**Comment by githubbar** [comment]
Ok, done. hope I did it right

**Comment by FrittenKeeZ** [comment]
You did! :)
