### ISSUE TITLE
Unable to run demos

### ISSUE THREAD

**Issue by rob7hunter** [oddgames/UIToolkit#29]
I tried opening KitchenSink.unity in DemoScenes/ and got 4 warnings for "The referenced script on this behavior is missing."

Same for ColorPicker.unity.

**Comment by prime31** [comment]
If you arent opening them with Unity Pro you may have to reconnect the prefabs. we will eventually get around to releasing unitypackages again once the next update is ready.

**Comment by rob7hunter** [comment]
I am using Unity Pro. Here's more precise steps. Downloaded the latest
version as a zip file (b9aade8), unpack, navigate to
Assets/DemoScenes/ColorPicker.unity and double-click.

Unity imports the assets, and then actually I get a bunch of
errors/warnings (in my original report, I only reported what happened the _second_ project I opened). Anyway, the
errors/warnings look like this:
- assets is missing its meta data file. Reimporting asset.
- library/inputmanager.asset is missing its meta data file. Reimporting asset.
- ...
- Failed to create cache directory for asset Assets

There are probably 50 items total.

**Comment by prime31** [comment]
Hmmm, I am seeing this is well along with some Library paths not being
writeable after import. I wonder if it's due to Unity version
mismatches. In the meantime, I just added a unitypackage of the
current release to the downloads section.

Mike

On Thu, Nov 3, 2011 at 12:39 PM, Rob Hunter
reply@reply.github.com
wrote:

**Comment by rob7hunter** [comment]
Thanks, the unitypackage worked for me. Different versions sounds plausible. I'm on 3.4.2f2 fwiw, but I assume if that's the problem it's more about projects _created_ with a different version.

**Comment by prime31** [comment]
I am still in the process of downloading 3.4.2f2. I had to revert back
to 3.4.1 due to the Android bug but it is supposedly fixed with the
version that dropped yesterday.

Mike

On Thu, Nov 3, 2011 at 1:29 PM, Rob Hunter
reply@reply.github.com
wrote:
