### ISSUE TITLE
Making git repository Unity friendly(er)

### ISSUE THREAD

**Issue by nsxdavid** [oddgames/UIToolkit#49]
This repository contains a lot of binary files that it should not.

Here are the guidelines for using Unity with SCM:

http://unity3d.com/support/documentation/Manual/ExternalVersionControlSystemSupport.html

Currently if I clone down this repo, it can be a bit of a mess to get it working.  The primary problem is that there are various binary files in the Library folder that are causing the issues.

The .gitignore seems to be correct (I have to look closer) but never-the-less files are being tracked and thus flowing into the commits that should not.

I'd like to clean this up, but wanted to check first to make sure there wasn't some reason this wasn't already done as per the documentation.

**Comment by prime31** [comment]
It technically should only have .asset database files from the Library
folder. All else should be ignored based on the .gitignore file.

Mike

On Dec 3, 2011, at 1:13 PM, David Whatley
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
Yup, I've cleaned that up in my clone.  Can't push directly.  Do you favor I work in my own fork or in a branch off of this repo (and do pull requets from the branch?)

**Comment by prime31** [comment]
I should probably add both of you guys to the main repo. You both know
what your doing and know UIToolkits internals well. We can then just
do standard feature branches and merge back to mainline when the
branch is ready. I'll get on that as soon as I'm back to a computer.

Mike

On Dec 3, 2011, at 2:33 PM, David Whatley
reply@reply.github.com
wrote:

**Comment by nsxdavid** [comment]
Sounds good.

**Comment by nsxdavid** [comment]
This has been merged into mainline
