### ISSUE TITLE
How to remove UIText?

### ISSUE THREAD

**Issue by swisscoder** [oddgames/UIToolkit#59]
How do you clean up the scene, if you want to remove UIText?

they not have a destroy method on them. I can set the UITextInstance to "" and destroy all it's child UISprites, but then the UITextInstances remain in the scene.

What't the preferred way to get rid of them?

**Comment by FrittenKeeZ** [comment]
I've added a destroy method to UITextInstance that will be merged into the main project as soon as my code has been reviewed.

**Comment by swisscoder** [comment]
ok, nice. Thank you!

Will have to try it out :)
