### ISSUE TITLE
UISprite - is there any 'alpha blending' effect?

### ISSUE THREAD

**Issue by raytsang** [oddgames/UIToolkit#72]
Is there any method performing ‘Add’ produces a glow effect.

**Comment by FrittenKeeZ** [comment]
I don't understand the question. Could you elaborate please?

**Comment by raytsang** [comment]
http://www.codeproject.com/KB/GDI-plus/CsTranspTutorial1/Figure2.jpg

something like 'real' world 0% transparent

**Comment by acron0** [comment]
raytsang, there's nothing to stop you using your own shaders with UITK

**Comment by rotorz** [comment]
I believe all you need to do is copy the shader that ships with UITK and replace the blend mode with:

```
Blend One One
```
