### ISSUE TITLE
UIToolkit crashed upon opening downloaded zip

### ISSUE THREAD

**Issue by tomoprime** [oddgames/UIToolkit#81]
UIToolkit crashed upon opening downloaded zip. I'm using the latest stable version of Unity 3.4.2f2. Just wondering if anyone else had experienced this on Mac OS Lion?

Can someone advise on what parts of the package that I need to copy in say an empty project to begin working with it?

I copied the plugins folder for now. I wish I could see the demos but breaking the cache / temp would mean that all demo scenes would have broken links to assets and scripts.

**Comment by acron0** [comment]
UIToolkit requires Unity 3.5. There was a significant change involved with the layout and structure of the meta data associated with the project so I would attempt an upgrade before we investigate this.

**Comment by tomoprime** [comment]
I upgraded. I had errors while loading up the color picker example. Missing assets or something.

Question: 
Edit - noticed someone posted a fix for destroying Containers in "Pull requests", so I omitted the 1st question

Under Panel / Layout the AddChild(blah blah... allow you to group together UI objects for alignment. So I can have multiple sliders, buttons and toggles say in one panel. What about if I want to group and tie text ui objects to a toggle box or slider like in giving it a label? How would I parent these for alignment as AddChild only seems to support Sprite UI objects?

Edit - I figured out a way of doing it: 
                // Toggle Button and label
        var toggle1 = UIToggleButton.create( UI.Find("kitchenSinkSheet"), "cbUnchecked.png", "cbChecked.png", "cbDown.png", -10, 0 );
        text1 = text.addTextInstance("Use Accel", 30, 0, 0.5f, 5, Color.yellow, UITextAlignMode.Right, UITextVerticalAlignMode.Top );
        toggle1.onToggle += ( sender, newValue ) => hSlider.hidden = !newValue;
        toggle1.selected = true;  
        toggle1.scale=new Vector3(.5f,.5f,1f);
        text1.parentUIObject=toggle1;

ToDo - It may be nice to allow labels to be build into UIObjects with options for changing the default font and color...

Speaking of Alignment. I like how you can staple objects to portions of the screen based upon a percentage. I would like to see this as a feature for animations too. At the moment everything is a Vector3. You know with those PositionTo/From's animations. I had saved time by aligning UI objects using percentages but then lost time when trying to animate to new positions based on Vectors... It would be nice to be able to say Animate to the center of the screen or to the Right Top and so on by %. Just a thought.

Also I have added a few things in UI.cs that maybe of use to others where would I upload my ideas to share with everyone?
