### ISSUE TITLE
Can `hidden` property be moved into `UIObject`?

### ISSUE THREAD

**Issue by kruncher** [oddgames/UIToolkit#95]
It would be useful if all `UIObject`'s exposed a `hidden` property.

**Comment by prime31** [comment]
UIObject has no view component to hide. What would the use case be to
hide an object that can't be seen?

Mike

On Mar 19, 2012, at 7:04 PM, kruncher
reply@reply.github.com
wrote:

**Comment by kruncher** [comment]
For example.

``` cs
UIObject[] hud = UIObject[] { scoreIcon, scoreTextInstance, pauseButton };

// Hide HUD
foreach (UIObject item in hud)
    item.hidden = true;
```

It seems as though containers do not support text instances nor the nesting of containers.

I am fairly new to UIToolkit, is there a higher level interface common to all view components? Like `Control` in a forms application?

**Comment by prime31** [comment]
If you have a look through the interfaces you will be able to quickly
see how things are grouped. The first concrete class with a view
(verts) is UISprite.

Mike

On Mar 19, 2012, at 7:13 PM, kruncher
reply@reply.github.com
wrote:
