### ISSUE TITLE
UIToolkit doesn't work on Android.

### ISSUE THREAD

**Issue by AdamWorld** [oddgames/UIToolkit#98]
Hi!
I try to build & run any demo on Android but it fails with iphone related error.
I updated most up-to-date version of UIToolkit.
So I revert to old version but it works fine.
New version seems error on Android.

Thank you.
Adam.

**Comment by kruncher** [comment]
I too am experiencing the same problems:

```
Assets/Plugins/UIToolkit/UI.cs(79,58): error CS0103: The name `iPhone' does not exist in the current context
Assets/Plugins/UIToolkit/UI.cs(81,21): error CS0019: Operator `&&' cannot be applied to operands of type `bool' and `object'
Error building Player because scripts had compiler errors
```

**Comment by PapaWhiskey65** [comment]
change the code in ui.cs to the following

```
#if UNITY_EDITOR || UNITY_STANDALONE_OSX || UNITY_STANDALONE_WIN || UNITY_WEBPLAYER || UNITY_ANDROID
    var deviceAllowsHD = true;
#else
    var deviceAllowsHD = ( allowPod4GenHD && iPhone.generation == iPhoneGeneration.iPodTouch4Gen ) || iPhone.generation != iPhoneGeneration.iPodTouch4Gen;
#endif
```

or change the "#else" to "#elif UNITY_IPHONE" but then you'll need to define the var outside the #if block

**Comment by kruncher** [comment]
Cheers, this appears to solve the build issue for me.

Though I still can't test my game because the painfully slow Android emulator says that the game has stopped working (before anything has shown on screen)... I'm going to need an actual device sooner rather than later!

**Comment by prime31** [comment]
latest push has android allowing HD now
